
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const BoardDocuments = lazy(() => import("./pages/BoardDocuments.tsx"));
const BoardUpdates = lazy(() => import("./pages/BoardUpdates.tsx"));
const Chat = lazy(() => import("./pages/Chat.tsx"));
const MeetingDetail = lazy(() => import("./pages/MeetingDetail.tsx"));
const Meetings = lazy(() => import("./pages/Meetings.tsx"));
const Tasks = lazy(() => import("./pages/Tasks.tsx"));
const TranslationManagement = lazy(() => import("./pages/TranslationManagement.tsx"));
const UserManagement = lazy(() => import("./pages/UserManagement.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/board-documents", element: <UserGuard><BoardDocuments /></UserGuard>},
	{ path: "/boarddocuments", element: <UserGuard><BoardDocuments /></UserGuard>},
	{ path: "/board-updates", element: <UserGuard><BoardUpdates /></UserGuard>},
	{ path: "/boardupdates", element: <UserGuard><BoardUpdates /></UserGuard>},
	{ path: "/chat", element: <UserGuard><Chat /></UserGuard>},
	{ path: "/meeting-detail", element: <UserGuard><MeetingDetail /></UserGuard>},
	{ path: "/meetingdetail", element: <UserGuard><MeetingDetail /></UserGuard>},
	{ path: "/meetings", element: <UserGuard><Meetings /></UserGuard>},
	{ path: "/tasks", element: <UserGuard><Tasks /></UserGuard>},
	{ path: "/translation-management", element: <UserGuard><TranslationManagement /></UserGuard>},
	{ path: "/translationmanagement", element: <UserGuard><TranslationManagement /></UserGuard>},
	{ path: "/user-management", element: <UserGuard><UserManagement /></UserGuard>},
	{ path: "/usermanagement", element: <UserGuard><UserManagement /></UserGuard>},

];
