name: Terraform CI/CD

on:
  push:
    branches:
      - main  # run when pushing to main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      HETZNER_TOKEN: ${{ secrets.HETZNER_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="hcloud_token=${{ secrets.HETZNER_TOKEN }}" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
